language: ruby
cache: bundler
rvm:
  - 2.1.1
before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/config.yml.sample config/config.yml
  - RAILS_ENV=test bundle exec rake db:migrate
