web:
  build: .
  command: bundle exec rackup -p 3000
  volumes:
    - .:/srv/app
  ports:
    - "80:3000"
  links:
    - db
    - redis

worker:
  build: .
  command: bundle exec rake resque:work
  volumes:
    - .:/srv/app
  links:
    - db
    - redis

db:
  image: postgres

redis:
  image: redis

